default_language_version:
  python: python3
fail_fast: true

repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.2.1
    hooks:
      - id: prettier
        args: [--prose-wrap=always]
        types: [markdown]
        files: |
          (?x)^(
            README.md|
            mkdocs/docs/
          )
