site_name: "Code Everything: Fundamentals of Computer Vision"
site_url: "https://zendikit.github.io/code-everything-fundamentals-of-computer-vision/"
copyright: "&copy; 2021 Zendikit"
site_dir: "../docs"
strict: true

nav:
  - Home: index.md
  - Text:
    - Introduction: 000_introduction/introduction.md

markdown_extensions:
  - markdown_katex:
      no_inline_svg: True
      insert_fonts_css: True
      # macro-file: macros.tex
