site_name: "Code Everything: Fundamentals of Computer Vision"

nav:
  - Home: index.md
  - About: test.md

# theme: readthedocs

markdown_extensions:
  - markdown_katex:
      no_inline_svg: True
      insert_fonts_css: True
      # macro-file: macros.tex
